---
- hosts: all
  user: root
  become: true
  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml
  vars_files:
  - vars/local.yml
  - vars/fastcgi.conf.yml
  - vars/http.conf.yml
  - vars/https.conf.yml
  - vars/paths.yml
  - vars/versions.yml
