---
- name: copy php fpm upstream
  template: src=templates/conf-http/upstream-php-fpm.conf.j2
            dest={{ nginx_root }}/conf/http/upstream-php-fpm.conf
            owner=root
            group=root
            mode=0644
#  notify: restart nginx
